### ISSUE TITLE
bashbrew: Generic support for Docker Registries

### ISSUE THREAD

**Issue by jsok** [docker-library/bashbrew#13]
Right now the tool depends on the [DockerHub API](https://github.com/docker-library/official-images/blob/936ab74bae3cc42e3dc8d6bec01a454fd4b81af6/bashbrew/go/src/bashbrew/hub.go#L34) which isn't compatible with the [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/).

This makes `bashbrew` less portable and not suited for managing docker libraries running on other registries.

Would you be open to supporting patches that:
1. Provide config flag(s) to instruct `bashbrew` to use the official registry API for tag metadata scraping
1. Add the necessary authentication support to use the registry API

**Comment by tianon** [comment]
Sorry for the delay here -- I've moved this to the new https://github.com/docker-library/bashbrew (something we'd been thinking about for a while, but your comment helped encourage us to finally really pull the trigger).

As long as the impact is low, I think that sounds pretty reasonable.  I'm kind of curious why it's not enabled in the default `https` handler for https://github.com/go-git/go-git -- any ideas?
