### ISSUE TITLE
Deprecate single line library file format

### ISSUE THREAD

**Issue by yosifkit** [docker-library/bashbrew#16]
This issue is to declare and track the intent to drop the single line format. This is mostly to make parsing errors clear (rather than the current of printing both errors and having the user guess which is the issue).

We don't have releases often, so it would make most sense to pick some dates at which it would begin printing warnings on the single line format and then a date at which it will fail to parse them.  Rough timeline would be to ~start warning sometime in September and then drop support at the end of the year~ *completely remove the single line format before November*. 

Alternatively we could skip the warning period and just make a new release with single line parsing dropped since bashbrew is still pre `1.0`. We would need to migrate any library files in official-images before the release.

(RFC 2822 manifest file format was added in June 2016: https://github.com/docker-library/official-images/pull/1793)

- [x] ~deprecate by adding warnings to bashbrew~ *skipping*
  - [x] ~make a release~
- [ ] remove single line parsing
  - [ ] make a release (maybe a major bump like 1.0)
- [x] convert any current `library/` files in official-images to RFC 2822 format (`grep -E ': (http|git).*@' library/*`)
  - [x] arangodb
  - [x] clearlinux
  - [x] couchbase
  - [x] sourcemage
  - [x] thrift

**Comment by tianon** [comment]
cc affected image maintainers:

- `arangodb`: @fceller @dothebart @KVS85
- `clearlinux`: @bryteise
- `couchbase`: @ceejatec @cb-robot
  (it would be good to add a human to the `library/couchbase` maintainers list)
- `sourcemage`: @vaygr
- `thrift`: @ahawkins

If you have automation producing your `library/foo` file content, please update it to generate the newer RFC2822-based format (if you don't take action, we'll be updating the files for you at some point) -- you can see the automatic conversion `bashbrew` has been doing below:

```console
$ bashbrew cat arangodb
Maintainers: Frank Celler <info@arangodb.com> (@fceller), Wilfried Goesgens <w.goesgens@arangodb.org> (@dothebart), Vadim Kondratyev <vadim@arangodb.org> (@KVS85)
GitFetch: refs/heads/*

Tags: 3.4, 3.4.10
GitRepo: https://github.com/arangodb/arangodb-docker
GitCommit: 26a907ab559d36823a7de6d1e2eeee24aeade1e2
Directory: alpine/3.4.10

Tags: 3.5, 3.5.5
GitRepo: https://github.com/arangodb/arangodb-docker
GitCommit: 26a907ab559d36823a7de6d1e2eeee24aeade1e2
Directory: alpine/3.5.5.1

Tags: 3.6, 3.6.5, latest
GitRepo: https://github.com/arangodb/arangodb-docker
GitCommit: 26a907ab559d36823a7de6d1e2eeee24aeade1e2
Directory: alpine/3.6.5


$ bashbrew cat clearlinux
Maintainers: William Douglas <william.douglas@intel.com> (@bryteise)
GitFetch: refs/heads/*

Tags: latest, base
GitRepo: git://github.com/clearlinux/docker-brew-clearlinux
GitCommit: 998f90b8d0b5262b0faf50033cb5d962596090de


$ bashbrew cat couchbase
Maintainers: Couchbase Docker Team <docker@couchbase.com> (@couchbase)
GitFetch: refs/heads/*

Tags: latest, enterprise, 6.6.0, enterprise-6.6.0
GitRepo: https://github.com/couchbase/docker
GitCommit: f0ab8e5c7fc1091465097dc231cd5586f3eb7355
Directory: enterprise/couchbase-server/6.6.0

Tags: community, community-6.5.1
GitRepo: https://github.com/couchbase/docker
GitCommit: f17df7695bbd6efb756b90b683bd5f34d08b5708
Directory: community/couchbase-server/6.5.1


$ bashbrew cat sourcemage
Maintainers: Vlad Glagolev <stealth@sourcemage.org> (@vaygr)
GitFetch: refs/heads/*

Tags: latest, 0.62
GitRepo: git://github.com/vaygr/docker-sourcemage
GitCommit: a03bbe3ae7bbb839c3c69afd4504ca336f7b9cb9
Directory: stable


$ bashbrew cat thrift
Maintainers: Adam Hawkins <hi@ahawkins.me> (@ahawkins)
GitFetch: refs/heads/*

Tags: 0.9, 0.9.3
GitRepo: git://github.com/ahawkins/docker-thrift
GitCommit: d322572f7dd6ea468a14a4d832fbec26f152c71e
Directory: 0.9

Tags: 0.10, 0.10.0
GitRepo: git://github.com/ahawkins/docker-thrift
GitCommit: e1f81dfe3e8fac5588e12d2b880166d1743dbecd
Directory: 0.10

Tags: 0.11, 0.11.0
GitRepo: git://github.com/ahawkins/docker-thrift
GitCommit: 00e197d889426695446baec4e034b5ddbb15bcb3
Directory: 0.11

Tags: 0.12, 0.12.0, latest
GitRepo: git://github.com/ahawkins/docker-thrift
GitCommit: d7e73876549d205898b1922bcbf69e74ef11c288
Directory: 0.12
```

**Comment by bryteise** [comment]
Update for Clear Linux in https://github.com/docker-library/official-images/pull/8569

**Comment by KVS85** [comment]
Update for ArangoDB in https://github.com/docker-library/official-images/pull/8578

**Comment by ceejatec** [comment]
> (it would be good to add a human to the library/couchbase maintainers list)

Not sure I'm clear why? We keep the email alias we specify up-to-date with whoever is responsible for the images we author. If we specified individuals in the library/couchbase file, it would be duplicating that information, and possibly fall out of date.

**Comment by tianon** [comment]
> > (it would be good to add a human to the library/couchbase maintainers list)
> 
> Not sure I'm clear why? We keep the email alias we specify up-to-date with whoever is responsible for the images we author. If we specified individuals in the library/couchbase file, it would be duplicating that information, and possibly fall out of date.

It's very rare that we use the email address of the maintainers line (which is why it's actually optional in the official format) -- we almost exclusively communicate with image maintainers via GitHub mentions, so having to go look up a list of folks who've touched the file to give them a CC (and hope they're still involved in the image maintenance) is a bit tedious.

**Comment by ceejatec** [comment]
Ah, I see. Well, I did change the @ reference in our control file to be @cb-robot, which is a GitHub user account whose email address is associated with the same humans as our docker email list; hopefully that gets the job done!
