### ISSUE TITLE
question: convincing generate.sh to do a buildkit build

### ISSUE THREAD

**Issue by grooverdan** [docker-library/bashbrew#98]
I'm trying to work out how to make generate.sh output a buildkit build on this criteria. Where is `.builder = "buildkit"` set?
 
https://github.com/docker-library/bashbrew/blob/10343d331c8ea6e3ed289c613deb681abeb03381/scripts/github-actions/generate.sh#L81

This is so I can access the COPY --chmod synax ([ref](https://docs.docker.com/reference/dockerfile/#copy---chown---chmod)) and can avoid another layer like:
```
https://github.com/MariaDB/mariadb-docker/pull/593/files#diff-06aaf016508acc42e173e462fdda2de06e46f80227174d6bcaf20019657a5efeR31-R33
```

**Comment by yosifkit** [comment]
Adding `Builder: buildkit` to the output of your `generate-stackbrew-library.sh` should do the trick.

**Comment by grooverdan** [comment]
thank you.
